# Generated by Django 3.1.1 on 2020-09-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200916_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
