# Generated by Django 3.1.1 on 2020-12-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200918_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
